#!/bin/sh

PREFIX="${1}"

case "${2}" in
    "qigong")
	SBINTARGET="qigong qigenkey crtelnet"
	INITTARGET="qigong"
	DEFAULTTARGET="qigong"
	MANTARGET="qigong.8"
	;;
    "qicollect")
	SBINTARGET="qicollect"
	INITTARGET="qicollect"
	MANTARGET="qicollect.8"
	SRVTARGET="qicollect"
	;;
    *)
	SBINTARGET="qigong qicollect qigenkey crtelnet"
	INITTARGET="qigong qicollect"
	DEFAULTTARGET="qigong"
	MANTARGET="qigong.8 qicollect.8"
	SRVTARGET="qicollect"
	;;
esac

if [ "$3" ]
then
    ABSOLUTE="$3"
else
    ABSOLUTE=YES
fi

checkcreatedestdir () {
    DEST="$1"
    DESTDIR=`echo "$DEST" | rev | cut -d/ -f2- | rev`
    if [ ! -d "${DESTDIR}" ]
    then
	echo ici mkdir -m755 -p "$DESTDIR"
	mkdir -m755 -p "$DESTDIR"
    fi
}

BACKUP_TAG=`date +"%Y%m%d"`

if [ ! -d "${PREFIX}" ]
then
    echo mkdir -m755 -p "${PREFIX}"
    mkdir -m755 -p "${PREFIX}"
fi

for NOM in ${SBINTARGET}
do
    DEST="${PREFIX}/sbin/${NOM}"
    checkcreatedestdir "${DEST}"
    if [ -e "${DEST}" ]
    then
	mv "${DEST}" "${DEST}-${BACKUP_TAG}"
    fi
    cp "${NOM}" "${DEST}"
    chmod 755 "${DEST}"
done

for NOM in ${INITTARGET}
do
    if [ "$ABSOLUTE" = YES ]
    then
	DEST="/etc/init.d/${NOM}"
    else
	DEST="${ABSOLUTE}/etc/init.d/${NOM}"
    fi

    checkcreatedestdir "${DEST}"
    if [ -e "${DEST}" ]
    then
	mv "${DEST}" "${DEST}-${BACKUP_TAG}"
    fi
    cp "${NOM}".rc "${DEST}"
    chmod 755 "${DEST}"
done

if [ ${DEFAULTTARGET} ]
then
    for NOM in ${DEFAULTTARGET}
    do
	if [ "$ABSOLUTE" = YES ]
	then
	    DEST="/etc/default/${NOM}"

	    checkcreatedestdir "${DEST}"
	    if [ -e "${DEST}" ]
	    then
		mv "${DEST}" "${DEST}-${BACKUP_TAG}"
	    fi
	    if [ "$ABSOLUTE" = YES ]
	    then
		echo "KEYFILE=\""`hostname`.key.priv"\"" > "${DEST}"
		mkdir -p /etc/qigong
		mkdir -p /etc/qigong/keys
		chmod 750 /etc/qigong
		chmod 700 /etc/qigong/keys
		cd /etc/qigong/keys && qigenkey `hostname`
	    fi
	    chmod 644 "${DEST}"
	fi
    done
fi

if [ ${SRVTARGET} ]
then
    for NOM in ${SRVTARGET}
    do
	if [ "$ABSOLUTE" = YES ]
	then
	    mkdir -p /srv/"$NOM"
	    chown "$NOM":"$NOM" /srv/"$NOM"
	    chmod 755 /srv/"$NOM"

	    mkdir -p /srv/"$NOM"/rrd
	    chown "$NOM":"$NOM"  /srv/"$NOM"/rrd
	    chmod 755 -p /srv/"$NOM"/rrd
	fi
    done
fi

for NOM in ${MANTARGET}
do
    DEST="${PREFIX}/share/man/man"`echo "$NOM" | rev | cut -d. -f1 | rev`"/$NOM"
    checkcreatedestdir "${DEST}"
    cp "$NOM" "${DEST}"
    chmod 644 "$DEST"
done

