#!/bin/sh

PREFIX="${1}"

case "${2}" in
    "qigong")
	SBINTARGET="qigong"
	INITTARGET="qigong"
	;;
    "qicollect")
	SBINTARGET="qicollect"
	INITTARGET="qicollect"
	;;
    *)
	SBINTARGET="qigong qicollect"
	INITTARGET="qigong qicollect"
	;;
esac

BACKUP_TAG=`date +"%Y%m%d"`

if [ ! -d "${PREFIX}" ]
then
    echo "${0} error : ${PREFIX} isn't a directory ?"
    exit 1
fi

for NOM in ${SBINTARGET}
do
    DEST="${PREFIX}/sbin/${NOM}"
    if [ -e "${DEST}" ]
    then
	mv "${DEST}" "${DEST}-${BACKUP_TAG}"
    fi
    cp "${NOM}" "${DEST}"
    chmod 755 "${DEST}"
done

for NOM in ${INITTARGET}
do
    DEST="/etc/init.d/${NOM}"
    if [ -e "${DEST}" ]
    then
	mv "${DEST}" "${DEST}-${BACKUP_TAG}"
    fi
    cp "${NOM}".rc "${DEST}"
    chmod 755 "${DEST}"
done
