#!/bin/sh

PREFIX="${1}"

case "${2}" in
    "qigong")
	SBINTARGET="qigong"
	INITTARGET="qigong"
	MANTARGET="qigong.8"
	;;
    "qicollect")
	SBINTARGET="qicollect"
	INITTARGET="qicollect"
	MANTARGET="qicollect.8"
	;;
    *)
	SBINTARGET="qigong qicollect"
	INITTARGET="qigong qicollect"
	;;
esac

if [ "$3" ]
then
    ABSOLUTE="$3"
else
    ABSOLUTE=YES
fi

checkcreatedestdir () {
    DEST="$1"
    DESTDIR=`echo "$DEST" | rev | cut -d/ -f2- | rev`
    if [ ! -d "${DESTDIR}" ]
    then
	echo ici mkdir -m755 -p "$DESTDIR"
	mkdir -m755 -p "$DESTDIR"
    fi
}

BACKUP_TAG=`date +"%Y%m%d"`

if [ ! -d "${PREFIX}" ]
then
    echo mkdir -m755 -p "${PREFIX}"
    mkdir -m755 -p "${PREFIX}"
fi

for NOM in ${SBINTARGET}
do
    DEST="${PREFIX}/sbin/${NOM}"
    checkcreatedestdir "${DEST}"
    if [ -e "${DEST}" ]
    then
	mv "${DEST}" "${DEST}-${BACKUP_TAG}"
    fi
    cp "${NOM}" "${DEST}"
    chmod 755 "${DEST}"
done

for NOM in ${INITTARGET}
do
    if [ "$ABSOLUTE" = YES ]
    then
	DEST="/etc/init.d/${NOM}"
    else
	DEST="${ABSOLUTE}/etc/init.d/${NOM}"
    fi

    checkcreatedestdir "${DEST}"
    if [ -e "${DEST}" ]
    then
	mv "${DEST}" "${DEST}-${BACKUP_TAG}"
    fi
    cp "${NOM}".rc "${DEST}"
    chmod 755 "${DEST}"
done

for NOM in ${MANTARGET}
do
    DEST="${PREFIX}/share/man/man"`echo "$NOM" | rev | cut -d. -f1 | rev`"/$NOM"
    checkcreatedestdir "${DEST}"
    cp "$NOM" "${DEST}"
    chmod 644 "$DEST"
done

