#!/bin/bash

set -e

case "$1" in
  configure)
    if ! getent passwd qicollect >/dev/null
    then
	adduser --disabled-password --quiet --system		\
	    --home /srv/qicollect				\
	    --gecos "qigong collecting daemon" --group qicollect
    fi
    chown root:qicollect /etc/qicollect/keys
    chmod 750 /etc/qicollect/keys

    mkdir -p /srv/qicollect/rrd
    chown qicollect:qicollect /srv/qicollect/rrd
    chmod 755 /srv/qicollect/rrd

    update-rc.d qicollect defaults

    if which invoke-rc.d >/dev/null 2>&1; then
	invoke-rc.d qicollect restart
    else
	/etc/init.d/qicollect restart
    fi
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
  ;; 
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

